### ISSUE TITLE
API Issues

### ISSUE THREAD

**Issue by csimlinger** [alyf-de/frappe_sipgate#5]
Hi,

thanks for open sourcing the project! :)

I was wondering what kind of issues did you experience with the API?
Are the issues related to sipgate or to the code? I just want to make sure their API works like intended before I sign a contract there.

Thanks a lot!

**Comment by barredterra** [comment]
The endpoint we are using disappeared from the docs and suddenly started throwing errors. Sipgate's developer support took a look at our code and, after 3 weeks, was able to provide a solution to the latter: we now have to supply the ID of an existing contact as part of the data. Here's the fix: https://github.com/alyf-de/frappe_sipgate/commit/28d06d0777ea293f9e598c3d6622422a72c4f26f . Apart from this, we've had no issues with the API.

**Comment by csimlinger** [comment]
Thanks a lot for letting me know!
